name: Build GO binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: '1.24'

    - name: Installing protoc-gen-go
      run: |
        go get github.com/golang/protobuf/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc   

    - name: Run check
      run: make build
